version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: uid
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: marsrover
    container_name: marsrover-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - marsrover

  db:
    image: mysql:5.7
    container_name: marsrover-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rovers_db
      MYSQL_ROOT_PASSWORD: nasa
      MYSQL_PASSWORD: rovers_db
      MYSQL_USER: rovers_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/db:/var/lib/database
      - ./docker/mysql/initdb.d/:/docker-entrypoint-initdb.d
    networks:
      - marsrover

  nginx:
    image: nginx:alpine
    container_name: marsrover-nginx
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - marsrover

networks:
  marsrover:
    driver: bridge
